// Fake data for a list of people
const fakeData = [
  {
    id: 3,
    firstName: 'Pratham',
    lastName: 'Singh',
    phoneNumber: '+9876543210',
    profileImageLink: 'https://picsum.photos/200',
    email: 'pratham.singh@example.com',
    type:"Personal",
    time:"now",
    title: "You liked my work??"
    ,content:"if yes, you can Hire me"
  },
    {
      id: 1,
      firstName: 'John',
      lastName: 'Doe',
      phoneNumber: '+1234567890',
      profileImageLink: 'https://source.unsplash.com/user/c_v_r/100x100',
      email: 'john.doe@example.com',
      type:"Facebook DM",
      time:"10 min",
      title:"Awsome Product",
      content:"Hey There | probably did one of the best.."
    },
    
    {
      id: 4,
      firstName: 'Alice',
      lastName: 'Johnson',
      phoneNumber: '+8765432109',
      profileImageLink: 'https://source.unsplash.com/user/erondu/100x100',
      email: 'alice.johnson@example.com',
      type: "WhatsApp Message",
      time: "5 min",
      title: "Quick Question",
      content: "Hi, can you help me with a quick question?",
    },
    {
      id: 5,
      firstName: 'Bob',
      lastName: 'Williams',
      phoneNumber: '+1987654321',
      profileImageLink: 'https://source.unsplash.com/user/beatriz-perez/100x100',
      email: 'bob.williams@example.com',
      type: "Email",
      time: "15 min",
      title: "Project Collaboration",
      content: "I'm interested in collaborating on a project. Let's discuss!",
    },
 
    {
      id: 8,
      firstName: 'Oliver',
      lastName: 'Brown',
      phoneNumber: '+9988776655',
      profileImageLink: 'https://source.unsplash.com/user/anniespratt/100x100',
      email: 'oliver.brown@example.com',
      type: "LinkedIn Connection Request",
      time: "2 hours",
      title: "Networking Opportunity",
      content: "I came across your profile and would like to connect for networking.",
    },
    {
      id: 9,
      firstName: 'Sophia',
      lastName: 'Miller',
      phoneNumber: '+5544332211',
      profileImageLink: 'https://source.unsplash.com/user/amyshamblen/100x100',
      email: 'sophia.miller@example.com',
      type: "SMS",
      time: "3 hours",
      title: "Quick Message",
      content: "Just wanted to drop a quick message and say hello!",
    },
    {
      id: 6,
      firstName: 'Emma',
      lastName: 'Davis',
      phoneNumber: '+7654321098',
      profileImageLink: 'https://source.unsplash.com/user/kellysikkema/100x100',
      email: 'emma.davis@example.com',
      type: "Instagram DM",
      time: "20 min",
      title: "Photo Collaboration",
      content: "Loving your photography! Would you be interested in a collaboration?",
    },
    {
      id: 2,
      firstName: 'Jane',
      lastName: 'Smith',
      phoneNumber: '+9876543210',
      profileImageLink: 'https://www.infogrepper.com/wp-content/uploads/2022/10/image-url-for-testing.png',
      email: 'jane.smith@example.com',
      type:"Facebook Post",
      time:"10 min",
      title: "Available in store??"
      ,content:"Hi do you have any T-shirt available"
    }, 
    {
      id: 7,
      firstName: 'Ella',
      lastName: 'Taylor',
      phoneNumber: '+1122334455',
      profileImageLink: 'https://source.unsplash.com/user/chrisjoelcampbell/100x100',
      email: 'ella.taylor@example.com',
      type: "Twitter Mention",
      time: "1 hour",
      title: "Great Tweet!",
      content: "Your recent tweet was awesome. Keep up the good work!",
    },
  ];
  
  export default fakeData;
  